version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: marsroverdb
      POSTGRES_USER: mars
      POSTGRES_PASSWORD: roverpass
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mars"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - net
    ports:
      - "5432:5432"

  web:
    build: ./web
    container_name: web
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: mars
      DB_PASSWORD: roverpass
      DB_NAME: marsroverdb
    networks:
      - net

networks:
  net:
    driver: bridge
